/**
 * Tileset creation helpers (`docs/03-data-model.md` §4).
 *
 * Kept separate from `state/documentStore.ts` the same way `model/tags.ts`
 * is: pure construction logic with no store/undo awareness, so it is testable
 * standalone and reusable from both the (future) tile stamp tool and this
 * phase's programmatic CRUD.
 */

import { allocateEmptyTileBuffer, getTileBuffer } from './tileBuffers';
import { flipTileH, flipTileV, transposeTile } from './tilemapRender';
import type { Tileset, TilesetId } from './types';

/**
 * A brand-new tileset with its mandatory empty tile at index 0
 * (`docs/03-data-model.md` §4: "index 0 is always the empty tile"). The empty
 * tile's own buffer is allocated immediately — it is a real, fully
 * transparent, drawable tile, not a placeholder id with nothing behind it.
 */
export function createTileset(
  makeId: () => string,
  name: string,
  tileWidth: number,
  tileHeight: number,
): Tileset {
  const id: TilesetId = makeId();
  const emptyTileId = makeId();
  allocateEmptyTileBuffer(emptyTileId, tileWidth, tileHeight);
  return {
    id,
    name,
    tileWidth,
    tileHeight,
    tiles: [{ id: emptyTileId }],
  };
}

/**
 * Crop `rect` (in `buffer`'s own local coordinates) out of a pixel buffer,
 * or `undefined` when `rect` does not fit entirely inside it — the tile
 * stamp tool's "capture a selection as a tile" workflow
 * (`docs/08-roadmap.md` Phase 6). Straight alpha throughout, same as every
 * other pixel buffer in the app — this is a crop, not a resample, so there is
 * no premultiplication concern to get wrong.
 */
export function extractTilePixels(
  buffer: Uint8ClampedArray,
  bufferWidth: number,
  bufferHeight: number,
  rect: { x: number; y: number; width: number; height: number },
): Uint8ClampedArray | undefined {
  if (
    rect.width <= 0 ||
    rect.height <= 0 ||
    rect.x < 0 ||
    rect.y < 0 ||
    rect.x + rect.width > bufferWidth ||
    rect.y + rect.height > bufferHeight
  ) {
    return undefined;
  }
  const out = new Uint8ClampedArray(rect.width * rect.height * 4);
  for (let y = 0; y < rect.height; y++) {
    const srcRowStart = ((rect.y + y) * bufferWidth + rect.x) * 4;
    const dstRowStart = y * rect.width * 4;
    out.set(buffer.subarray(srcRowStart, srcRowStart + rect.width * 4), dstRowStart);
  }
  return out;
}

/** Byte-exact comparison — pixel content, not just length. */
export function tilePixelsEqual(a: Uint8ClampedArray, b: Uint8ClampedArray): boolean {
  if (a.length !== b.length) return false;
  for (let i = 0; i < a.length; i++) {
    if (a[i] !== b[i]) return false;
  }
  return true;
}

export interface TileMatch {
  /** Index of the existing `TileEntry` that reproduces the captured pixels. */
  index: number;
  /** Apply these flags (`model/tileIds.ts`) to the existing entry to reproduce them. */
  flipH: boolean;
  flipV: boolean;
  transpose: boolean;
}

/**
 * Auto-deduplication (`docs/08-roadmap.md` Phase 6): find an existing tile in
 * `tileset` whose stored pixels equal `pixels`, under any of the 8 ways a
 * square tile can be reoriented from `flipH`/`flipV`/`transpose`
 * (`model/tileIds.ts`) — gap-closure follow-up to the original "flip-only"
 * partial, which chased only 4 of the 8.
 *
 * **Why all 8 are genuinely distinct comparisons, not some redundant subset**:
 * a square's own symmetry group (dihedral, order 8 — identity, 3 rotations,
 * 4 reflections) is generated by any two of its reflections, and `flipH`
 * (reflect across the vertical axis) plus `flipV` (reflect across the
 * horizontal axis) only generate the *Klein four-group* subgroup `{identity,
 * flipH, flipV, flipH∘flipV}` — the 180° rotation and the two axis
 * reflections, 4 elements. `transpose` (reflect across the main diagonal) is
 * a reflection that is *not* in that subgroup, so composing it with each of
 * the 4 already-covered elements reaches the other coset — the identity
 * diagonal, the anti-diagonal, and the two 90° rotations — the remaining 4
 * elements, for 8 total with no overlap. This is not merely abstract group
 * theory: `resolveTilePixels` (`model/tilemapRender.ts`) applies the same
 * three flags to a tile in a fixed order (transpose, then flipH, then
 * flipV), so the 8 combinations checked here are exactly the 8 pixel
 * transforms a real tile placement could ever request — reusing an entry
 * under any of them is guaranteed to render back to the captured pixels
 * exactly.
 *
 * Reuses `tilePixelsEqual` (byte-exact) fed the same `transposeTile`/
 * `flipTileH`/`flipTileV` primitives the renderer itself uses, rather than a
 * second comparison path — a transpose is just a different pixel-index
 * remapping through the same equality check the flip cases already used.
 * `transposeTile` is itself a no-op on a non-square tile (only well-defined
 * for `tileWidth === tileHeight`, per its own doc comment) — the 4
 * transpose-inclusive checks below then trivially reduce to the 4 flip-only
 * ones already covered, so a non-square tileset degrades to exactly its
 * previous flip-only behaviour rather than misbehaving.
 */
export function findMatchingTile(
  tileset: Tileset,
  pixels: Uint8ClampedArray,
): TileMatch | undefined {
  const { tileWidth: w, tileHeight: h } = tileset;
  for (let index = 0; index < tileset.tiles.length; index++) {
    const buf = getTileBuffer(tileset.tiles[index].id);
    if (!buf || buf.length !== pixels.length) continue;

    if (tilePixelsEqual(buf, pixels)) {
      return { index, flipH: false, flipV: false, transpose: false };
    }
    if (tilePixelsEqual(flipTileH(buf, w, h), pixels)) {
      return { index, flipH: true, flipV: false, transpose: false };
    }
    if (tilePixelsEqual(flipTileV(buf, w, h), pixels)) {
      return { index, flipH: false, flipV: true, transpose: false };
    }
    if (tilePixelsEqual(flipTileV(flipTileH(buf, w, h), w, h), pixels)) {
      return { index, flipH: true, flipV: true, transpose: false };
    }

    const transposed = transposeTile(buf, w, h);
    if (tilePixelsEqual(transposed, pixels)) {
      return { index, flipH: false, flipV: false, transpose: true };
    }
    if (tilePixelsEqual(flipTileH(transposed, w, h), pixels)) {
      return { index, flipH: true, flipV: false, transpose: true };
    }
    if (tilePixelsEqual(flipTileV(transposed, w, h), pixels)) {
      return { index, flipH: false, flipV: true, transpose: true };
    }
    if (tilePixelsEqual(flipTileV(flipTileH(transposed, w, h), w, h), pixels)) {
      return { index, flipH: true, flipV: true, transpose: true };
    }
  }
  return undefined;
}
